# Generated by Django 5.1.1 on 2025-04-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=100)),
                ('start_day', models.DateField()),
                ('sessions_number', models.IntegerField()),
                ('middle_term_point', models.IntegerField()),
                ('final_term_point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(default='other', max_length=10)),
                ('start_at', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(default='other', max_length=10)),
                ('start_at', models.DateField()),
                ('credits', models.IntegerField()),
                ('graduate_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_day', models.DateField()),
                ('number_of_weeks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_order', models.IntegerField()),
                ('status', models.CharField(default='absent', max_length=10)),
                ('class_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.class_student')),
            ],
        ),
        migrations.AddField(
            model_name='class_student',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.lecturer'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.student'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credits', models.IntegerField()),
                ('dean', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='class_student',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.subject'),
        ),
        migrations.AddField(
            model_name='class_student',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.term'),
        ),
    ]
