# Generated by Django 5.1.1 on 2025-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_student',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='class_student',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
