# Generated by Django 5.1.1 on 2025-04-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_class_student_end_time_class_student_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_student',
            name='class_code',
        ),
    ]
