# Generated by Django 5.1.1 on 2025-04-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_remove_class_student_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_student',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='sessions_number',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='term',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('sessions_number', models.IntegerField()),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.lecturer')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.subject')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.term')),
            ],
        ),
        migrations.AddField(
            model_name='class_student',
            name='class_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.class'),
        ),
    ]
