# Generated by Django 5.1.1 on 2025-04-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_remove_class_student_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_student',
            name='final_term_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class_student',
            name='middle_term_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
