# Generated by Django 5.1.1 on 2025-04-17 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_class_student_final_term_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_order', models.IntegerField()),
                ('class_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_site.class')),
            ],
        ),
    ]
