# Generated by Django 5.1.1 on 2025-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_date',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance_date',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
